;; leanrn anacoda mode
(add-hook 'python-mode-hook
          (lambda ()
            (set (make-local-variable 'company-backends) '(company-anaconda company-dabbrev))
            (define-key python-mode-map (kbd "s-g r") 'anaconda-mode-find-references)
            (define-key python-mode-map (kbd "s-g d") 'anaconda-mode-find-definitions)
            (define-key python-mode-map (kbd "s-g s") 'anaconda-mode-find-assignments)
            (define-key python-mode-map (kbd "s-g h") 'anaconda-mode-show-doc)
            (define-key python-mode-map (kbd "s-i") 'python-start-or-switch-repl)
            (define-key python-mode-map (kbd "s-n") 'python-shell-send-buffer)
            (define-key python-mode-map (kbd "s-N") 'python-shell-send-buffer-switch)
            (define-key python-mode-map (kbd "s-m") 'python-shell-send-defun)
            (define-key python-mode-map (kbd "s-M") 'python-shell-send-defun-switch)
            (define-key python-mode-map (kbd "s-r") 'python-shell-send-region)
            (define-key python-mode-map (kbd "s-R") 'python-shell-send-region-switch)
            (define-key python-mode-map (kbd "s-h d") 'helm-ag)
            (define-key python-mode-map (kbd "s-h t") 'helm-ag-this-file)
            (define-key python-mode-map (kbd "s-h b") 'helm-ag-buffers)
            (define-key python-mode-map (kbd "s-h p") 'helm-ag-project-root)
            (define-key python-mode-map (kbd "s-h D") 'helm-do-ag)
            (define-key python-mode-map (kbd "s-h T") 'helm-do-ag-this-file)
            (define-key python-mode-map (kbd "s-h B") 'helm-do-ag-buffers)
            (define-key python-mode-map (kbd "s-h P") 'helm-do-ag-project-root)
            (define-key python-mode-map (kbd "s-h c") 'helm-ag-clear-stack)
            (define-key python-mode-map (kbd "s-h o") 'helm-ag-pop-stack)
            (company-quickhelp-mode)
            )
          )

(add-hook 'python-mode-hook 'anaconda-mode)
(add-hook 'python-mode-hook 'eldoc-mode)
