(add-hook 'go-mode-hook
          (lambda ()
            (set (make-local-variable 'company-backends) '(company-dabbrev company-files))
            (define-key go-mode-map (kbd "s-g h") 'godoc-at-point)

            (define-key go-mode-map (kbd "s-g i a") 'go-import-add)
            (define-key go-mode-map (kbd "s-g i r") 'go-remove-unused-imports)
            (define-key go-mode-map (kbd "s-g i g") 'go-goto-imports)

            (define-key go-mode-map (kbd "s-g e b") 'go-play-buffer)
            (define-key go-mode-map (kbd "s-g e r") 'go-play-region)
            (define-key go-mode-map (kbd "s-g e d") 'go-download-play)
            (define-key go-mode-map (kbd "s-g e d") 'go-download-play)
            (define-key go-mode-map (kbd "s-g e d") 'go-download-play)

            (define-key go-mode-map (kbd "s-g r") 'go-guru-referrers)
            (define-key go-mode-map (kbd "s-g d") 'go-guru-definition)
            (define-key go-mode-map (kbd "s-g s") 'go-guru-callers)
            (define-key go-mode-map (kbd "s-g c") 'go-guru-callstack)
            (define-key go-mode-map (kbd "s-g t") 'go-guru-callees)
            (define-key go-mode-map (kbd "s-g m") 'go-guru-implements)
            (define-key go-mode-map (kbd "s-g x") 'spacemacs/go-run-main)

            (define-key go-mode-map (kbd "s-h d") 'helm-ag)
            (define-key go-mode-map (kbd "s-h t") 'helm-ag-this-file)
            (define-key go-mode-map (kbd "s-h b") 'helm-ag-buffers)
            (define-key go-mode-map (kbd "s-h p") 'helm-ag-project-root)
            (define-key go-mode-map (kbd "s-h D") 'helm-do-ag)
            (define-key go-mode-map (kbd "s-h T") 'helm-do-ag-this-file)
            (define-key go-mode-map (kbd "s-h B") 'helm-do-ag-buffers)
            (define-key go-mode-map (kbd "s-h P") 'helm-do-ag-project-root)
            (define-key go-mode-map (kbd "s-h c") 'helm-ag-clear-stack)
            (define-key go-mode-map (kbd "s-h o") 'helm-ag-pop-stack)
            ))
