;; leanrn anacoda mode
(add-hook 'python-mode-hook
          (lambda ()
            (set (make-local-variable 'company-backends) '(company-anaconda company-dabbrev))
            (local-set-key (kbd "C-r") 'anaconda-mode-find-references)
            (local-set-key (kbd "C-d") 'anaconda-mode-find-definitions)
            (local-set-key (kbd "C-u") 'anaconda-mode-find-assignments)
            (local-set-key (kbd "C-y") 'anaconda-mode-show-doc)
            (local-set-key (kbd "s-i") 'python-start-or-switch-repl)
            (local-set-key (kbd "s-n") 'python-shell-send-buffer)
            (local-set-key (kbd "s-N") 'python-shell-send-buffer-switch)
            (local-set-key (kbd "s-m") 'python-shell-send-defun)
            (local-set-key (kbd "s-M") 'python-shell-send-defun-switch)
            (local-set-key (kbd "s-r") 'python-shell-send-region)
            (local-set-key (kbd "s-R") 'python-shell-send-region-switch)
            (company-quickhelp-mode)
            ))

(add-hook 'python-mode-hook 'anaconda-mode)
(add-hook 'python-mode-hook 'eldoc-mode)
